apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-auth
data:
  username: {{ default "" .Values.api.username | b64enc | quote }}
  password: {{ default "" .Values.api.password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ecsConnection.name }}-auth
data:
  username: {{ default "" .Values.ecsConnection.username | b64enc | quote }}
  password: {{ default "" .Values.ecsConnection.password | b64enc | quote }}

---
{{ if .Values.serviceCatalog }}
apiVersion: v1
kind: Secret
metadata:
  name: ecs-broker-catalog-credentials
type: Opaque
data:
  username: {{ randAlphaNum 10 | b64enc | quote }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{ end }}
